name: Android Build

on:
  workflow_call:
    secrets:
      ANDROID_KEY_ALIAS:
        required: true
      ANDROID_KEY_PASSWORD:
        required: true
      ANDROID_STORE_FILE:
        required: true
      ANDROID_STORE_PASSWORD:
        required: true
      DUTCHRAILWAYS_TRAVELINFOAPI_KEY:
        required: true
      GOOGLE_SERVICES_JSON:
        required: true

concurrency:
  group: android-build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up JDK
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'adopt'
          cache: 'gradle'

      # Permissions for Gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # Add Google Services File
      - name: Add google-services.json
        run: |
          echo "${{ secrets.GOOGLE_SERVICES_JSON }}" > ./app/google-services.json.b64
          base64 -d ./app/google-services.json.b64 > ./app/google-services.json

      # Add key store file
      - name: Add key store file
        run: |
          echo "${{ secrets.ANDROID_STORE_FILE }}" > ./app/key.jks.b64
          base64 -d ./app/key.jks.b64 > ./app/key.jks

      # Build
      - name: Build with Gradle
        run: ./gradlew compileDebugSources compileDebugUnitTestSources compileReleaseSources
        env:
          DUTCHRAILWAYS_TRAVELINFOAPI_KEY: ${{ secrets.DUTCHRAILWAYS_TRAVELINFOAPI_KEY }}
          ANDROID_STORE_PASSWORD: ${{ secrets.ANDROID_STORE_PASSWORD }}
          ANDROID_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
          ANDROID_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
