name: Android build

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v2

      # Set up JDK
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'adopt'
          cache: 'gradle'

      # Permissions for Gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # Add Google Services File
      - name: Add google-services.json
        run: |
          cd app
          cat > google-services.json << ENDOFFILE 
          ${{ secrets.GOOGLE_SERVICES_JSON }} 
          ENDOFFILE
          cd ..

      # Build
      - name: Build with Gradle
        run: ./gradlew bundleRelease assembleRelease
        env:
          DUTCHRAILWAYS_TRAVELINFOAPI_KEY: ${{ secrets.DUTCHRAILWAYS_TRAVELINFOAPI_KEY }}
          ANDROID_STORE_PASSWORD: ${{ secrets.ANDROID_STORE_PASSWORD }}
          ANDROID_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
          ANDROID_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}

      # Move artifacts
      - name: Move artifacts
        run: |
          mkdir out
          mv app/build/outputs/bundle/release/app-release.aab /out/TraiNL-release.aab
          find app/build/outputs/bundle -type f -name 'app-*-release.aab' -exec sh -c 'x="{}"; mv "$x" "TraiNL-${x#\"app-\"}"' \;
          mv app/build/outputs/apk/release/app-release.apk /out/TraiNL-release.apk
          find app/build/outputs/apk -type f -name 'app-*-release.apk' -exec sh -c 'x="{}"; mv "$x" "TraiNL-${x#\"app-\"}"' \;

      # Upload artifacts
      - uses: actions/upload-artifact@v2
        with:
          name: 'TraiNL release binaries'
          path: out/*
          if-no-files-found: error
