name: Android tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:

      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v2

      # Set up JDK
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'adopt'
          cache: 'gradle'

      # Permissions for Gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # Add Google Services File
      - name: Add google-services.json
        run: |
          cd app
          cat > google-services.json << ENDOFFILE
          ${{ secrets.GOOGLE_SERVICES_JSON }}
          ENDOFFILE
          cd ..

      # Test
      - name: Test with Gradle
        run: ./gradlew test
        env:
          DUTCHRAILWAYS_TRAVELINFOAPI_KEY: ${{ secrets.DUTCHRAILWAYS_TRAVELINFOAPI_KEY }}
          ANDROID_STORE_PASSWORD: ${{ secrets.ANDROID_STORE_PASSWORD }}
          ANDROID_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
          ANDROID_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
